### PR TITLE
LRAC-11874 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-11874

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! Waiting for someone from backend to review the backend part, so I can forward after it

**Comment by marcosapmf** [comment]
resent to https://github.com/pt-liferay-solutions/liferay-portal/pull/2143

**Pull request closed without merging**
